#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-kubernetes-client
Version  : 3.0.0
Release  : 4
URL      : https://github.com/fabric8io/kubernetes-client/archive/v3.0.0.tar.gz
Source0  : https://github.com/fabric8io/kubernetes-client/archive/v3.0.0.tar.gz
Source1  : https://repo.maven.apache.org/maven2/io/fabric8/kubernetes-model-generator/2.0.0/kubernetes-model-generator-2.0.0.pom
Source2  : https://repo.maven.apache.org/maven2/io/fabric8/kubernetes-model/2.0.0/kubernetes-model-2.0.0.jar
Source3  : https://repo.maven.apache.org/maven2/io/fabric8/kubernetes-model/2.0.0/kubernetes-model-2.0.0.pom
Source4  : https://repo1.maven.org/maven2/io/fabric8/kubernetes-client-project/3.0.0/kubernetes-client-project-3.0.0.pom
Source5  : https://repo1.maven.org/maven2/io/fabric8/kubernetes-client/3.0.0/kubernetes-client-3.0.0.jar
Source6  : https://repo1.maven.org/maven2/io/fabric8/kubernetes-client/3.0.0/kubernetes-client-3.0.0.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-kubernetes-client-data = %{version}-%{release}

%description
# Kubernetes & OpenShift 3 Java Client [![Join the chat at https://gitter.im/fabric8io/kubernetes-client](https://badges.gitter.im/fabric8io/kubernetes-client.svg)](https://gitter.im/fabric8io/kubernetes-client?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)
This client provides access to the full [Kubernetes](http://kubernetes.io/) &
[OpenShift 3](http://openshift.org/) REST APIs via a fluent DSL.

%package data
Summary: data components for the mvn-kubernetes-client package.
Group: Data

%description data
data components for the mvn-kubernetes-client package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/fabric8/kubernetes-model-generator/2.0.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/io/fabric8/kubernetes-model-generator/2.0.0/kubernetes-model-generator-2.0.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/fabric8/kubernetes-model/2.0.0
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/io/fabric8/kubernetes-model/2.0.0/kubernetes-model-2.0.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/fabric8/kubernetes-model/2.0.0
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/io/fabric8/kubernetes-model/2.0.0/kubernetes-model-2.0.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/fabric8/kubernetes-client-project/3.0.0
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/io/fabric8/kubernetes-client-project/3.0.0/kubernetes-client-project-3.0.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/fabric8/kubernetes-client/3.0.0
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/io/fabric8/kubernetes-client/3.0.0/kubernetes-client-3.0.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/io/fabric8/kubernetes-client/3.0.0
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/io/fabric8/kubernetes-client/3.0.0/kubernetes-client-3.0.0.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/io/fabric8/kubernetes-client-project/3.0.0/kubernetes-client-project-3.0.0.pom
/usr/share/java/.m2/repository/io/fabric8/kubernetes-client/3.0.0/kubernetes-client-3.0.0.jar
/usr/share/java/.m2/repository/io/fabric8/kubernetes-client/3.0.0/kubernetes-client-3.0.0.pom
/usr/share/java/.m2/repository/io/fabric8/kubernetes-model-generator/2.0.0/kubernetes-model-generator-2.0.0.pom
/usr/share/java/.m2/repository/io/fabric8/kubernetes-model/2.0.0/kubernetes-model-2.0.0.jar
/usr/share/java/.m2/repository/io/fabric8/kubernetes-model/2.0.0/kubernetes-model-2.0.0.pom
